### ISSUE TITLE
setup the database

### ISSUE THREAD

**Issue by arademaker** [jheek/cqpweb#1]
I got an error in the command

```
root@d2e1c68d2c44:/tmp/cwb# cd /var/www/CQPweb/bin
bash: cd: /var/www/CQPweb/bin: No such file or directory
```

any idea?

**Comment by jheek** [comment]
Could be a problem with the docker installation. These kind of problems occur often on windows machines (folders disappearing).
A factory reset of the docker machine usually fixes the problem. Although usually restarting the host machine also fixes the issue

**Comment by arademaker** [comment]
I found the problem, the `bin` directory is inside the folder `www`,  I didn't find the folder `CQPweb`.
